-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 5
-- Total Raw Fields: 23
-- ============================================================================

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_offices_held_district_abbreviation(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_offices_held_district_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_offices_held_office_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_offices_held_person_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_offices_held_term_duration_days(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_offices_holder_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_people_has_ever_been_us_senator(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_people_senator_term_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_person_residences_person_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_person_residences_state_abbreviation(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_person_residences_state_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_states_resident_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_offices_held_end_date(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_offices_held_rank(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_offices_held_start_date(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_offices_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_offices_requires_district(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_people_birth_date(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_people_is_historical(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_people_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_person_residences_end_date(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_person_residences_location_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_person_residences_source(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_person_residences_start_date(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_states_abbreviation(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_states_name(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_offices CASCADE;
DROP VIEW IF EXISTS vw_offices_held CASCADE;
DROP VIEW IF EXISTS vw_people CASCADE;
DROP VIEW IF EXISTS vw_person_residences CASCADE;
DROP VIEW IF EXISTS vw_states CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS offices CASCADE;
DROP TABLE IF EXISTS offices_held CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS person_residences CASCADE;
DROP TABLE IF EXISTS states CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

CREATE TABLE people (
  person_id                           INTEGER              PRIMARY KEY,
  name                                TEXT                ,
  wikidata_id                         TEXT                ,
  birth_date                          DATE                ,
  is_historical                       BOOLEAN             ,
  offices_held_list                   TEXT                ,
  residences_list                     TEXT                
);

CREATE TABLE offices (
  office_id                           INTEGER              PRIMARY KEY,
  name                                TEXT                ,
  wikidata_id                         TEXT                ,
  wikidata_property_id                TEXT                ,
  requires_district                   BOOLEAN             
);

CREATE TABLE states (
  state_id                            INTEGER              PRIMARY KEY,
  name                                TEXT                ,
  abbreviation                        TEXT                ,
  wikidata_id                         TEXT                
);

CREATE TABLE offices_held (
  office_held_id                      INTEGER              PRIMARY KEY,
  person                              INTEGER             ,
  office                              INTEGER             ,
  district                            INTEGER             ,
  start_date                          DATE                ,
  end_date                            DATE                ,
  rank                                TEXT                
);

CREATE TABLE person_residences (
  residence_id                        INTEGER              PRIMARY KEY,
  person                              INTEGER             ,
  state                               INTEGER             ,
  location_description                TEXT                ,
  start_date                          DATE                ,
  end_date                            DATE                ,
  source                              TEXT                
);

