-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

CREATE OR REPLACE FUNCTION get_offices_held_start_date(p_office_held_id TEXT)
RETURNS DATE AS $$
BEGIN
  RETURN (SELECT start_date FROM offices_held WHERE office_held_id = p_office_held_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_offices_held_end_date(p_office_held_id TEXT)
RETURNS DATE AS $$
BEGIN
  RETURN (SELECT end_date FROM offices_held WHERE office_held_id = p_office_held_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_offices_held_rank(p_office_held_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT rank FROM offices_held WHERE office_held_id = p_office_held_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_person_residences_location_description(p_residence_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT location_description FROM person_residences WHERE residence_id = p_residence_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_person_residences_start_date(p_residence_id TEXT)
RETURNS DATE AS $$
BEGIN
  RETURN (SELECT start_date FROM person_residences WHERE residence_id = p_residence_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_person_residences_end_date(p_residence_id TEXT)
RETURNS DATE AS $$
BEGIN
  RETURN (SELECT end_date FROM person_residences WHERE residence_id = p_residence_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_person_residences_source(p_residence_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT source FROM person_residences WHERE residence_id = p_residence_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_people_has_ever_been_us_senator(p_person_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (COUNTIFS((SELECT person FROM offices_held WHERE office_held_id = p_office_held_id), (SELECT person_id FROM people WHERE person_id = p_person_id), calc_offices_held_office_name(p_office_held_id), "US Senator") > 0)::boolean;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_people_senator_term_count(p_person_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM offices_held WHERE person = (SELECT person_id FROM people WHERE person_id = p_person_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_holder_count(p_office_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM offices_held WHERE office = (SELECT office_id FROM offices WHERE office_id = p_office_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_states_resident_count(p_state_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM person_residences WHERE state = (SELECT state_id FROM states WHERE state_id = p_state_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_held_person_name(p_office_held_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name::text FROM people WHERE person_id = (SELECT person FROM offices_held WHERE office_held_id = p_office_held_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_held_office_name(p_office_held_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name::text FROM offices WHERE office_id = (SELECT office FROM offices_held WHERE office_held_id = p_office_held_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_held_district_name(p_office_held_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name::text FROM states WHERE state_id = (SELECT district FROM offices_held WHERE office_held_id = p_office_held_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_held_district_abbreviation(p_office_held_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT abbreviation::text FROM states WHERE state_id = (SELECT district FROM offices_held WHERE office_held_id = p_office_held_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_people_name(p_person_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM people WHERE person_id = p_person_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_people_birth_date(p_person_id TEXT)
RETURNS DATE AS $$
BEGIN
  RETURN (SELECT birth_date FROM people WHERE person_id = p_person_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_people_is_historical(p_person_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (SELECT is_historical FROM people WHERE person_id = p_person_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_offices_name(p_office_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM offices WHERE office_id = p_office_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_offices_requires_district(p_office_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (SELECT requires_district FROM offices WHERE office_id = p_office_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_states_name(p_state_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name FROM states WHERE state_id = p_state_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_states_abbreviation(p_state_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT abbreviation FROM states WHERE state_id = p_state_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_offices_held_term_duration_days(p_office_held_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN NULL; -- Formula translation failed
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_person_residences_person_name(p_residence_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name::text FROM people WHERE person_id = (SELECT person FROM person_residences WHERE residence_id = p_residence_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_person_residences_state_name(p_residence_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT name::text FROM states WHERE state_id = (SELECT state FROM person_residences WHERE residence_id = p_residence_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_person_residences_state_abbreviation(p_residence_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT abbreviation::text FROM states WHERE state_id = (SELECT state FROM person_residences WHERE residence_id = p_residence_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

