-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 2
-- ============================================================================

CREATE OR REPLACE VIEW vw_is_everything_a_language WITH (security_invoker = ON) AS
SELECT
  t.is_everything_a_language_id,
  t.name,
  t.argument_name,
  t.argument_category,
  t.step_type,
  t.statement,
  t.formalization,
  t.related_candidate_name,
  t.related_candidate_id,
  t.evidence_from_rulebook,
  t.notes
FROM is_everything_a_language t;

CREATE OR REPLACE VIEW vw_language_candidates WITH (security_invoker = ON) AS
SELECT
  t.language_candidate_id,
  t.name,
  t.category,
  calc_language_candidates_family_fued_question(t.language_candidate_id) AS family_fued_question,
  calc_language_candidates_top_family_feud_answer(t.language_candidate_id) AS top_family_feud_answer,
  t.chosen_language_candidate,
  calc_language_candidates_family_feud_mismatch(t.language_candidate_id) AS family_feud_mismatch,
  t.has_syntax,
  t.has_identity,
  t.can_be_held,
  calc_language_candidates_has_grammar(t.language_candidate_id) AS has_grammar,
  t.requires_parsing,
  t.has_linear_decoding_pressure,
  t.is_stable_ontology_reference,
  t.dimensionality_while_editing,
  t.is_open_world,
  t.is_closed_world,
  calc_language_candidates_is_open_closed_world_conflicted(t.language_candidate_id) AS is_open_closed_world_conflicted,
  t.distance_from_concept,
  calc_language_candidates_is_description_of(t.language_candidate_id) AS is_description_of,
  calc_language_candidates_relationship_to_concept(t.language_candidate_id) AS relationship_to_concept,
  t.sort_order
FROM language_candidates t;

