-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 5
-- ============================================================================

CREATE OR REPLACE VIEW vw_people WITH (security_invoker = ON) AS
SELECT
  t.person_id,
  t.name,
  t.wikidata_id,
  t.birth_date,
  t.is_historical,
  t.offices_held_list,
  t.residences_list,
  calc_people_has_ever_been_us_senator(t.person_id) AS has_ever_been_us_senator,
  calc_people_senator_term_count(t.person_id) AS senator_term_count
FROM people t;

CREATE OR REPLACE VIEW vw_offices WITH (security_invoker = ON) AS
SELECT
  t.office_id,
  t.name,
  t.wikidata_id,
  t.wikidata_property_id,
  t.requires_district,
  calc_offices_holder_count(t.office_id) AS holder_count
FROM offices t;

CREATE OR REPLACE VIEW vw_states WITH (security_invoker = ON) AS
SELECT
  t.state_id,
  t.name,
  t.abbreviation,
  t.wikidata_id,
  calc_states_resident_count(t.state_id) AS resident_count
FROM states t;

CREATE OR REPLACE VIEW vw_offices_held WITH (security_invoker = ON) AS
SELECT
  t.office_held_id,
  t.person,
  t.office,
  t.district,
  t.start_date,
  t.end_date,
  t.rank,
  calc_offices_held_person_name(t.office_held_id) AS person_name,
  calc_offices_held_office_name(t.office_held_id) AS office_name,
  calc_offices_held_district_name(t.office_held_id) AS district_name,
  calc_offices_held_district_abbreviation(t.office_held_id) AS district_abbreviation,
  calc_offices_held_term_duration_days(t.office_held_id) AS term_duration_days
FROM offices_held t;

CREATE OR REPLACE VIEW vw_person_residences WITH (security_invoker = ON) AS
SELECT
  t.residence_id,
  t.person,
  t.state,
  t.location_description,
  t.start_date,
  t.end_date,
  t.source,
  calc_person_residences_person_name(t.residence_id) AS person_name,
  calc_person_residences_state_name(t.residence_id) AS state_name,
  calc_person_residences_state_abbreviation(t.residence_id) AS state_abbreviation
FROM person_residences t;

