-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE language_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE is_everything_a_language ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

