-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

INSERT INTO people (person_id, name, wikidata_id, birth_date, is_historical, offices_held_list, residences_list)
VALUES (1, 'Barack Obama', 'Q76', '1961-08-04', TRUE, NULL, NULL);

INSERT INTO people (person_id, name, wikidata_id, birth_date, is_historical, offices_held_list, residences_list)
VALUES (2, 'Jesus Christ', 'Q302', NULL, TRUE, NULL, NULL);

INSERT INTO people (person_id, name, wikidata_id, birth_date, is_historical, offices_held_list, residences_list)
VALUES (3, 'Santa Claus', 'Q42927', NULL, FALSE, NULL, NULL);

INSERT INTO offices (office_id, name, wikidata_id, wikidata_property_id, requires_district)
VALUES (1, 'US Senator', 'Q4416090', 'P39', TRUE);

INSERT INTO offices (office_id, name, wikidata_id, wikidata_property_id, requires_district)
VALUES (2, 'President of the United States', 'Q11696', 'P39', FALSE);

INSERT INTO offices (office_id, name, wikidata_id, wikidata_property_id, requires_district)
VALUES (3, 'Governor', 'Q132050', 'P39', TRUE);

INSERT INTO states (state_id, name, abbreviation, wikidata_id)
VALUES (1, 'Illinois', 'IL', 'Q1204');

INSERT INTO states (state_id, name, abbreviation, wikidata_id)
VALUES (2, 'New York', 'NY', 'Q1384');

INSERT INTO states (state_id, name, abbreviation, wikidata_id)
VALUES (3, 'Arizona', 'AZ', 'Q816');

INSERT INTO states (state_id, name, abbreviation, wikidata_id)
VALUES (4, 'Hawaii', 'HI', 'Q782');

INSERT INTO offices_held (office_held_id, person, office, district, start_date, end_date, rank)
VALUES (1, 1, 1, 1, '2005-01-03', '2008-11-16', 'normal');

INSERT INTO offices_held (office_held_id, person, office, district, start_date, end_date, rank)
VALUES (2, 1, 2, NULL, '2009-01-20', '2017-01-20', 'normal');

INSERT INTO person_residences (residence_id, person, state, location_description, start_date, end_date, source)
VALUES (1, 3, NULL, 'North Pole', NULL, NULL, 'folklore');

INSERT INTO person_residences (residence_id, person, state, location_description, start_date, end_date, source)
VALUES (2, 1, 4, 'Honolulu, Hawaii', '1961-08-04', '1979-06-01', 'biography');

