#!/bin/bash
# ============================================================================
# demo - Database Initialization Script
# ============================================================================
# Generated by rulebook-to-postgres tool
# ============================================================================

set -e  # Exit on error

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# SQL Files in execution order
# Base files (XX-*) are generated by ERB tooling
# Customization files (XXb-*) are for user modifications and won't be overwritten
SQL_FILES=(
    "${SCRIPT_DIR}/01-drop-and-create-tables.sql"
    "${SCRIPT_DIR}/01b-customize-schema.sql"
    "${SCRIPT_DIR}/02-create-functions.sql"
    "${SCRIPT_DIR}/02b-customize-functions.sql"
    "${SCRIPT_DIR}/03-create-views.sql"
    "${SCRIPT_DIR}/03b-customize-views.sql"
    "${SCRIPT_DIR}/04-create-policies.sql"
    "${SCRIPT_DIR}/04b-customize-policies.sql"
    "${SCRIPT_DIR}/05-insert-data.sql"
    "${SCRIPT_DIR}/05b-customize-data.sql"
)

# Default connection string
DEFAULT_CONN="postgresql://postgres@localhost:5432/cmcc-wiki-data"

# Get connection string from argument or use default
CONNECTION_STRING="${1:-$DEFAULT_CONN}"

echo "Initializing database: $CONNECTION_STRING"
echo ""

# Execute each SQL file
for sql_file in "${SQL_FILES[@]}"; do
    filename=$(basename "$sql_file")
    echo "Executing: $filename"
    psql "$CONNECTION_STRING" -f "$sql_file" -v ON_ERROR_STOP=1
    echo "✓ $filename completed"
    echo ""
done

echo "Database initialization complete!"
# end
